### ISSUE TITLE
[Bug]: ConcurrentModificationException

### ISSUE THREAD

**Issue by giladger** [transistorsoft/flutter_background_geolocation#1427]
### Required Reading

- [x] Confirmed

### Plugin Version

4.16.6

### Flutter Doctor

```shell
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.27.4, on macOS 15.0.1 24A348 darwin-arm64, locale en-IL)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] VS Code (version 1.96.0)
[✓] Connected device (5 available)
[✓] Network resources

• No issues found!
```

### Mobile operating-system(s)

- [ ] iOS
- [x] Android

### Device Manufacturer(s) and Model(s)

Samsung, One Plus so far - multiple devices and models

### Device operating-systems(s)

Android 12 & Android 14 so far

### What happened?

getting this new crash since upgrading from 4.15.5 to 4.16.6

java.util.ConcurrentModificationException: null
    at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1111)
    at java.util.ArrayList$Itr.next(ArrayList.java:1064)
    at com.transistorsoft.locationmanager.service.StopTimeoutEvaluator.a(SourceFile:1)
    at com.transistorsoft.locationmanager.service.GeofencingService.a(SourceFile:21)
    at com.transistorsoft.locationmanager.service.GeofencingService.a(SourceFile:2)
    at com.transistorsoft.locationmanager.service.GeofencingService$a.run
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
    at java.lang.Thread.run(Thread.java:1012)

### Plugin Code and/or Config

```dart
bg.Config(
        reset: true,
        debug: false,
        logLevel: bg.Config.LOG_LEVEL_ERROR,
        desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
        locationAuthorizationRequest: 'Always',
        backgroundPermissionRationale: bg.PermissionRationale(
        title: AppLocalizations.loc['geofence_permission_rationale_title'],
        message: AppLocalizations.loc['geofence_permission_rationale_message'],
        positiveAction: AppLocalizations.loc['geofence_permission_rationale_positive_action'],
        negativeAction: AppLocalizations.loc['geofence_permission_rationale_negative_action']
      ),
        geofenceModeHighAccuracy: true,
        disableElasticity: true,
        disableMotionActivityUpdates: true,
        showsBackgroundLocationIndicator: false,
        stopOnTerminate: false,
        startOnBoot: true,
        enableHeadless: true,
    )
```

### Relevant log output

```shell

```

**Comment by christocracy** [comment]
I think I see the problem.

**Comment by christocracy** [comment]
Are you able to reproduce this or it's being reported in crash-logs?

**Comment by christocracy** [comment]
Released fix to `4.16.7`.

**Comment by giladger** [comment]
> Are you able to reproduce this or it's being reported in crash-logs?

It was reported in crash-logs for 4% of the users. 
I'm releasing a version with 4.16.7 and will let you know if it's resolved.

Thanks for the quick response!

**Comment by giladger** [comment]
I'm getting this error when I build with the new version. 
Have encountered it before?

`ERROR:/.gradle/caches/transforms-3/8c27c0a7ed03dd4ba787170ad282d438/transformed/jetified-tslocationmanager-v21-3.6.5-runtime.jar: R8: java.lang.NullPointerException: Cannot invoke "String.length()" because "<parameter1>" is null

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:minifyReleaseWithR8'.
> com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: /.gradle/caches/transforms-3/8c27c0a7ed03dd4ba787170ad282d438/transformed/jetified-tslocationmanager-v21-3.6.5-runtime.jar:com/transistorsoft/locationmanager/activity/TSLocationManagerActivity$a.class`

**Comment by christocracy** [comment]
Does the error go away rolling back to previous version?

**Comment by christocracy** [comment]
Show me your android/app/build.gradle

**Comment by giladger** [comment]
Yes, build fine with 4.16.6

```
plugins {
    id 'org.jetbrains.kotlin.plugin.serialization' version '1.8.21'
}
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"
apply plugin: 'com.google.protobuf'

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

Project background_geolocation = project(':flutter_background_geolocation')
apply from: "${background_geolocation.projectDir}/background_geolocation.gradle"

android {
    compileSdkVersion rootProject.ext.compileSdkVersion

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        applicationId "com..."
        minSdkVersion 23
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        ndk {
            // Filter for architectures supported by Flutter
            // https://docs.flutter.dev/deployment/android#what-are-the-supported-target-architectures
            abiFilters 'armeabi-v7a', 'arm64-v8a', 'x86_64'
        }
    }

    signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile keystoreProperties['storeFile'] ? file(keystoreProperties['storeFile']) : null
            storePassword keystoreProperties['storePassword']
        }
    }
    buildTypes {
        release {
            shrinkResources false
            signingConfig signingConfigs.release
            proguardFiles "${background_geolocation.projectDir}/proguard-rules.pro"
        }
    }
    compileOptions {
        targetCompatibility = JavaVersion.VERSION_17
        sourceCompatibility = JavaVersion.VERSION_17
    }
    buildToolsVersion = '28.0.3'

    flavorDimensions "default"

    buildFeatures {
        viewBinding true
    }
}

flutter {
    source '../..'
}

repositories {
    mavenCentral()
}

protobuf {
    protoc {
        // for apple m1, add protoc_platform=osx-x86_64 in $HOME/.gradle/gradle.properties
        if (project.hasProperty('protoc_platform')) {
            artifact = "com.google.protobuf:protoc:3.20.0:${protoc_platform}"
        } else {
            artifact = "com.google.protobuf:protoc:3.20.0"
        }
    }
    plugins {
        javalite {
            if (project.hasProperty('protoc_platform')) {
                artifact = "com.google.protobuf:protoc-gen-javalite:3.0.0:${protoc_platform}"
            } else {
                artifact = "com.google.protobuf:protoc-gen-javalite:3.0.0"
            }
        }
    }
    generateProtoTasks {
        all().each { task ->
            task.builtins {
                java {
                    option "lite"
                }
            }
        }
    }
}

dependencies {
    api "androidx.appcompat:appcompat:1.1.0"
    implementation "androidx.work:work-runtime:2.8.1"
    implementation "androidx.work:work-runtime-ktx:2.8.1"
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation "androidx.core:core-ktx:1.2.0"

    // RxJava OkHttp
    implementation "com.google.code.gson:gson:2.8.6"
    implementation "com.squareup.okhttp3:okhttp:3.12.1"
    implementation "com.squareup.okhttp3:okhttp-urlconnection:3.12.1"
    // ==============================================================

    // RxJava
    implementation "io.reactivex.rxjava2:rxandroid:2.1.0"
    implementation "io.reactivex.rxjava2:rxjava:2.2.5"
    implementation "io.reactivex.rxjava2:rxkotlin:2.2.0"

    // GMS,    playServicesLocationVersion = "17.0.0"
    implementation "com.google.android.gms:play-services-maps:18.1.0"
    implementation "com.google.android.gms:play-services-location:${rootProject.ext.playServicesLocationVersion}"

    implementation 'com.google.protobuf:protobuf-javalite:3.18.3'
    implementation 'com.google.crypto.tink:tink-android:1.7.0'
    implementation 'com.polidea.rxandroidble2:rxandroidble:1.16.0'

    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    // tests
    testImplementation "junit:junit:4.12"
    androidTestImplementation "androidx.test:runner:1.2.0"
    androidTestImplementation "androidx.test.espresso:espresso-core:3.2.0"

    implementation "org.jetbrains.kotlinx:kotlinx-serialization-json:1.6.0"
}

apply plugin: 'com.google.firebase.crashlytics'
apply plugin: 'com.google.gms.google-services'
```

**Comment by christocracy** [comment]
>Yes, build fine with 4.16.6

I think I poisened the library building with too-advanced a jdk.  I recently had to upgrade my Android Studio and think my jdk got updated.

I'm going to push a new release built with jdk 17.

**Comment by christocracy** [comment]
published `4.16.8` just now.  Please try that out.

**Comment by christocracy** [comment]
>I think I poisoned the library building with too-advanced a jdk

Poisoned for people not using *Gradle Plugin v8.0+*, that is.

**Comment by giladger** [comment]
Still fails with the same issue with 4.16.8 :(
I too recently upgraded to Ladybug, but it broke some many things that I had to revert back to Koala

**Comment by christocracy** [comment]
Please try installing from master (so we can get this right without releasing new versions to pub.dev).  Adjust your pubspec.yaml as follows:

```yaml
dependencies:
  flutter_background_geolocation:
    git:
      url: https://github.com/transistorsoft/flutter_background_geolocation.git
```

```
$ flutter pub get
```

**Comment by giladger** [comment]
Still the same error

**Comment by christocracy** [comment]
I've pushed to a branch `release-4.16.9` now.  Adjust your pubspec as follows:

```yaml
dependencies:
  flutter_background_geolocation:
    git:
      url: https://github.com/transistorsoft/flutter_background_geolocation.git
      ref: release-4.16.9
```

**Comment by christocracy** [comment]
Try again:  `flutter pub get`

**Comment by giladger** [comment]
Works 🎉 
I'll release and will let you know.

Thanks again!

**Comment by christocracy** [comment]
Great.  I had my local jdk install with homebrew at SDK 22.  I build the library with a custom gradle command in console, which uses jdk from homebrew, not the one configured in Android Studio.

**Comment by christocracy** [comment]
`4.16.9` is published.  Revert your pubspec back.

**Comment by giladger** [comment]
The original issue was indeed resolved in 4.16.9

Thanks again for the quick response!
