### ISSUE TITLE
[HeadlessTask] waiting for client to initialize

### ISSUE THREAD

**Issue by miguelflores1993** [transistorsoft/flutter_background_geolocation#715]
**Your Environment**
* Plugin version: ^4.3.3
* Platform: Android
* flutter 2.10.0
* Device manufacturer / model: SAMSUMG A70

* Plugin config
```
void backgroundFetchHeadlessTask(HeadlessTask task) async {
  var taskId = task.taskId;
  var timeout = task.timeout;
  if (timeout) {
    print("[BackgroundFetch] Headless task timed-out: $taskId");
    BackgroundFetch.finish(taskId);
    return;
  }
  print("[BackgroundFetch] Headless event received: $taskId");
  if (taskId == 'com.deltaxlat.appdriver') {
    addLocalGpsHeadLess();
  }
  if (taskId == 'com.deltaxlat.appdriver.tasks') {
    syncHeadlessTasks();
  }
  if (taskId == 'com.deltaxlat.appdriver.multipoint') {
    syncHeadlessTasksMultipoint();
  }
  if (taskId == 'com.deltaxlat.appdriver.locations') {
    syncHeadlessCheckPoints();
  }
  BackgroundFetch.finish(taskId);
}
```

```
 await BackgroundFetch.configure(
        BackgroundFetchConfig(
          minimumFetchInterval: 60,
          forceAlarmManager: false,
          stopOnTerminate: false,
          startOnBoot: true,
          enableHeadless: true,
          requiresBatteryNotLow: false,
          requiresCharging: false,
          requiresStorageNotLow: false,
          requiresDeviceIdle: false,
          requiredNetworkType: NetworkType.NONE,
        ), (String taskId) async {
      if (taskId == 'com.deltaxlat.appdriver') {
        addLocalGps();
      }
      if (taskId == 'com.deltaxlat.appdriver.tasks') {
        syncTasks();
      }
      if (taskId == 'com.deltaxlat.appdriver.locations') {
        syncCheckPoints();
      }
       if (taskId == 'com.deltaxlat.appdriver.multipoint') {
        syncTasksMultipoint();
      }
      BackgroundFetch.finish(taskId);
    }, (String taskId) async {
      BackgroundFetch.finish(taskId);
    });
    await BackgroundFetch.scheduleTask(TaskConfig(
      taskId: "com.deltaxlat.appdriver",
      delay: 1800000,
      periodic: true,
      forceAlarmManager: false,
      stopOnTerminate: false,
      requiredNetworkType: NetworkType.NONE,
      startOnBoot: true,
      enableHeadless: true,
    ));
    await BackgroundFetch.scheduleTask(TaskConfig(
      taskId: "com.deltaxlat.appdriver.tasks",
      delay: 60000,
      periodic: true,
      forceAlarmManager: true,
      startOnBoot: true,
      requiredNetworkType: NetworkType.ANY,
      stopOnTerminate: false,
      enableHeadless: true,
    ));
    await BackgroundFetch.scheduleTask(TaskConfig(
      taskId: "com.deltaxlat.appdriver.locations",
      delay: 60000,
      periodic: true,
      requiredNetworkType: NetworkType.ANY,
      forceAlarmManager: true,
      stopOnTerminate: false,
      startOnBoot: true,
      enableHeadless: true,
    ));
    await BackgroundFetch.scheduleTask(TaskConfig(
      taskId: "com.deltaxlat.appdriver.multipoint",
      delay: 60000,
      periodic: true,
      requiredNetworkType: NetworkType.ANY,
      forceAlarmManager: true,
      stopOnTerminate: false,
      startOnBoot: true,
      enableHeadless: true,
    ));
```
```
 await bg.BackgroundGeolocation.ready(
        bg.Config(
          locationUpdateInterval: 60000,
          persistMode: bg.Config.PERSIST_MODE_GEOFENCE,
          desiredAccuracy: bg.Config.DESIRED_ACCURACY_HIGH,
          distanceFilter: 10000.0,
          enableHeadless: true,
          stopOnTerminate: false,
          startOnBoot: true,
          notification: bg.Notification(
            smallIcon: "drawable/ic_launcher_notification",
            priority: bg.Config.NOTIFICATION_PRIORITY_HIGH,
            sticky: true,
            title: user.profile?.firstName?.trim() != null ? '${user.profile?.firstName?.trim()} tienes una operación en curso' : "Operación en curso",
            strings: {},
            layout: "",
            actions: [],
            text: 'Recuerda completar todas tus tareas.',
          ),
          showsBackgroundLocationIndicator: true,
          backgroundPermissionRationale: bg.PermissionRationale(
            title: "Permitir que DeltaX acceda a la ubicación de este dispositivo incluso cuando esté cerca o no esté en uso?",
            message: "DeltaX recopila datos de tu ubicación, para realizar seguimiento a las cargas que transportas",
            positiveAction: "Cambiar a 'Permitir todo el tiempo'",
            negativeAction: "Cancelar",
          ),
          locationAuthorizationRequest: 'Always',
          debug: false,
        ),
      );

      await bg.BackgroundGeolocation.start();

      // bg.BackgroundGeolocation.setConfig(config)
      await BackgroundFetch.start();
```

**Debug logs**

- Android: `$ adb logcat`
```
02-24 16:18:42.181 25004 25004 D TSBackgroundFetch: [BGTask] timeout: com.deltaxlat.appdriver.locations
02-24 16:18:42.195 25004 25004 D TSBackgroundFetch: 💀 [HeadlessTask com.deltaxlat.appdriver.locations]
02-24 16:18:42.196 25004 25004 D TSBackgroundFetch: [BGTask] timeout: com.deltaxlat.appdriver.multipoint
02-24 16:18:42.209 25004 25004 D TSBackgroundFetch: 💀 [HeadlessTask com.deltaxlat.appdriver.multipoint]
02-24 16:18:42.210 25004 25004 D TSBackgroundFetch: [HeadlessTask] waiting for client to initialize
02-24 16:18:42.210 25004 25004 D TSBackgroundFetch: [HeadlessTask] waiting for client to initialize
02-24 16:18:42.210 25004 25004 D TSBackgroundFetch: [HeadlessTask] waiting for client to initialize
02-24 16:18:58.373 25004 25004 D TSBackgroundFetch: - Background Fetch event received: com.deltaxlat.appdriver.tasks
02-24 16:18:58.384 25004 25004 D TSBackgroundFetch: 💀 [HeadlessTask com.deltaxlat.appdriver.tasks]
02-24 16:18:58.384 25004 25004 D TSBackgroundFetch: [HeadlessTask] waiting for client to initialize
02-24 16:18:58.392 25004 25004 D TSBackgroundFetch: - Background Fetch event received: com.deltaxlat.appdriver.locations
02-24 16:18:58.399 25004 25004 D TSBackgroundFetch: 💀 [HeadlessTask com.deltaxlat.appdriver.locations]
02-24 16:18:58.399 25004 25004 D TSBackgroundFetch: [HeadlessTask] waiting for client to initialize
02-24 16:19:00.043 25004 25004 D TSBackgroundFetch: [BGTask] timeout: com.deltaxlat.appdriver.tasks
02-24 16:19:00.047 25004 25004 D TSBackgroundFetch: 💀 [HeadlessTask com.deltaxlat.appdriver.tasks]
02-24 16:19:00.048 25004 25004 D TSBackgroundFetch: [HeadlessTask] waiting for client to initialize
02-24 16:19:00.062 25004 25004 D TSBackgroundFetch: [BGTask] timeout: com.deltaxlat.appdriver.locations
02-24 16:19:00.066 25004 25004 D TSBackgroundFetch: 💀 [HeadlessTask com.deltaxlat.appdriver.locations]
02-24 16:19:00.068 25004 25004 D TSBackgroundFetch: [HeadlessTask] waiting for client to initialize
02-24 16:19:00.080 25004 25004 D TSBackgroundFetch: [BGTask] timeout: com.deltaxlat.appdriver.multipoint
02-24 16:19:00.084 25004 25004 D TSBackgroundFetch: 💀 [HeadlessTask com.deltaxlat.appdriver.multipoint]
02-24 16:19:00.092 25004 25004 D TSBackgroundFetch: [HeadlessTask] waiting for client to initialize
02-24 16:19:00.359 25004 25004 D TSBackgroundFetch: - Background Fetch event received: com.deltaxlat.appdriver.multipoint
02-24 16:19:00.365 25004 25004 D TSBackgroundFetch: 💀 [HeadlessTask com.deltaxlat.appdriver.multipoint]
02-24 16:19:00.365 25004 25004 D TSBackgroundFetch: [HeadlessTask] waiting for client to initialize
```

```
02-24 16:07:43.997  9956  9956 D TSBackgroundFetch: - configure
02-24 16:07:43.997  9956  9956 D TSBackgroundFetch: - start
02-24 16:07:43.997  9956  9956 D TSBackgroundFetch: - registerTask: flutter_background_fetch
02-24 16:07:44.000  9956  9956 D TSBackgroundFetch: {
02-24 16:07:44.000  9956  9956 D TSBackgroundFetch:   "taskId": "flutter_background_fetch",
02-24 16:07:44.000  9956  9956 D TSBackgroundFetch:   "isFetchTask": true,
02-24 16:07:44.000  9956  9956 D TSBackgroundFetch:   "minimumFetchInterval": 60,
02-24 16:07:44.000  9956  9956 D TSBackgroundFetch:   "stopOnTerminate": false,
02-24 16:07:44.000  9956  9956 D TSBackgroundFetch:   "requiredNetworkType": 0,
02-24 16:07:44.000  9956  9956 D TSBackgroundFetch:   "requiresBatteryNotLow": false,
02-24 16:07:44.000  9956  9956 D TSBackgroundFetch:   "requiresCharging": false,
02-24 16:07:44.000  9956  9956 D TSBackgroundFetch:   "requiresDeviceIdle": false,
02-24 16:07:44.000  9956  9956 D TSBackgroundFetch:   "requiresStorageNotLow": false,
02-24 16:07:44.000  9956  9956 D TSBackgroundFetch:   "startOnBoot": true,
02-24 16:07:44.000  9956  9956 D TSBackgroundFetch:   "jobService": "com.transistorsoft.flutter.backgroundfetch.HeadlessTask",
02-24 16:07:44.000  9956  9956 D TSBackgroundFetch:   "forceAlarmManager": false,
02-24 16:07:44.000  9956  9956 D TSBackgroundFetch:   "periodic": true,
02-24 16:07:44.000  9956  9956 D TSBackgroundFetch:   "delay": -1
02-24 16:07:44.000  9956  9956 D TSBackgroundFetch: }
02-24 16:07:44.039  9956  9956 D TSBackgroundFetch: - registerTask: com.deltaxlat.appdriver
02-24 16:07:44.039  9956  9956 D TSBackgroundFetch: {
02-24 16:07:44.039  9956  9956 D TSBackgroundFetch:   "taskId": "com.deltaxlat.appdriver",
02-24 16:07:44.039  9956  9956 D TSBackgroundFetch:   "isFetchTask": false,
02-24 16:07:44.039  9956  9956 D TSBackgroundFetch:   "minimumFetchInterval": 15,
02-24 16:07:44.039  9956  9956 D TSBackgroundFetch:   "stopOnTerminate": false,
02-24 16:07:44.039  9956  9956 D TSBackgroundFetch:   "requiredNetworkType": 0,
02-24 16:07:44.039  9956  9956 D TSBackgroundFetch:   "requiresBatteryNotLow": false,
02-24 16:07:44.039  9956  9956 D TSBackgroundFetch:   "requiresCharging": false,
02-24 16:07:44.039  9956  9956 D TSBackgroundFetch:   "requiresDeviceIdle": false,
02-24 16:07:44.039  9956  9956 D TSBackgroundFetch:   "requiresStorageNotLow": false,
02-24 16:07:44.039  9956  9956 D TSBackgroundFetch:   "startOnBoot": true,
02-24 16:07:44.039  9956  9956 D TSBackgroundFetch:   "jobService": "com.transistorsoft.flutter.backgroundfetch.HeadlessTask",
02-24 16:07:44.039  9956  9956 D TSBackgroundFetch:   "forceAlarmManager": false,
02-24 16:07:44.039  9956  9956 D TSBackgroundFetch:   "periodic": true,
02-24 16:07:44.039  9956  9956 D TSBackgroundFetch:   "delay": 1800000
02-24 16:07:44.039  9956  9956 D TSBackgroundFetch: }
02-24 16:07:44.069  9956  9956 D TSBackgroundFetch: - registerTask: com.deltaxlat.appdriver.tasks
02-24 16:07:44.069  9956  9956 D TSBackgroundFetch: {
02-24 16:07:44.069  9956  9956 D TSBackgroundFetch:   "taskId": "com.deltaxlat.appdriver.tasks",
02-24 16:07:44.069  9956  9956 D TSBackgroundFetch:   "isFetchTask": false,
02-24 16:07:44.069  9956  9956 D TSBackgroundFetch:   "minimumFetchInterval": 15,
02-24 16:07:44.069  9956  9956 D TSBackgroundFetch:   "stopOnTerminate": false,
02-24 16:07:44.069  9956  9956 D TSBackgroundFetch:   "requiredNetworkType": 1,
02-24 16:07:44.069  9956  9956 D TSBackgroundFetch:   "requiresBatteryNotLow": false,
02-24 16:07:44.069  9956  9956 D TSBackgroundFetch:   "requiresCharging": false,
02-24 16:07:44.069  9956  9956 D TSBackgroundFetch:   "requiresDeviceIdle": false,
02-24 16:07:44.069  9956  9956 D TSBackgroundFetch:   "requiresStorageNotLow": false,
02-24 16:07:44.069  9956  9956 D TSBackgroundFetch:   "startOnBoot": true,
02-24 16:07:44.069  9956  9956 D TSBackgroundFetch:   "jobService": "com.transistorsoft.flutter.backgroundfetch.HeadlessTask",
02-24 16:07:44.069  9956  9956 D TSBackgroundFetch:   "forceAlarmManager": true,
02-24 16:07:44.069  9956  9956 D TSBackgroundFetch:   "periodic": true,
02-24 16:07:44.069  9956  9956 D TSBackgroundFetch:   "delay": 60000
02-24 16:07:44.069  9956  9956 D TSBackgroundFetch: }
02-24 16:07:44.119  9956  9956 D TSBackgroundFetch: - registerTask: com.deltaxlat.appdriver.locations
02-24 16:07:44.119  9956  9956 D TSBackgroundFetch: {
02-24 16:07:44.119  9956  9956 D TSBackgroundFetch:   "taskId": "com.deltaxlat.appdriver.locations",
02-24 16:07:44.119  9956  9956 D TSBackgroundFetch:   "isFetchTask": false,
02-24 16:07:44.119  9956  9956 D TSBackgroundFetch:   "minimumFetchInterval": 15,
02-24 16:07:44.119  9956  9956 D TSBackgroundFetch:   "stopOnTerminate": false,
02-24 16:07:44.119  9956  9956 D TSBackgroundFetch:   "requiredNetworkType": 1,
02-24 16:07:44.119  9956  9956 D TSBackgroundFetch:   "requiresBatteryNotLow": false,
02-24 16:07:44.119  9956  9956 D TSBackgroundFetch:   "requiresCharging": false,
02-24 16:07:44.119  9956  9956 D TSBackgroundFetch:   "requiresDeviceIdle": false,
02-24 16:07:44.119  9956  9956 D TSBackgroundFetch:   "requiresStorageNotLow": false,
02-24 16:07:44.119  9956  9956 D TSBackgroundFetch:   "startOnBoot": true,
02-24 16:07:44.119  9956  9956 D TSBackgroundFetch:   "jobService": "com.transistorsoft.flutter.backgroundfetch.HeadlessTask",
02-24 16:07:44.119  9956  9956 D TSBackgroundFetch:   "forceAlarmManager": true,
02-24 16:07:44.119  9956  9956 D TSBackgroundFetch:   "periodic": true,
02-24 16:07:44.119  9956  9956 D TSBackgroundFetch:   "delay": 60000
02-24 16:07:44.119  9956  9956 D TSBackgroundFetch: }
```

```
02-24 16:14:26.321 25004 25004 D TSBackgroundFetch: - start
02-24 16:14:26.322 25004 25004 D TSBackgroundFetch: - registerTask: flutter_background_fetch
02-24 16:14:26.322 25004 25004 D TSBackgroundFetch: {
02-24 16:14:26.322 25004 25004 D TSBackgroundFetch:   "taskId": "flutter_background_fetch",
02-24 16:14:26.322 25004 25004 D TSBackgroundFetch:   "isFetchTask": true,
02-24 16:14:26.322 25004 25004 D TSBackgroundFetch:   "minimumFetchInterval": 60,
02-24 16:14:26.322 25004 25004 D TSBackgroundFetch:   "stopOnTerminate": false,
02-24 16:14:26.322 25004 25004 D TSBackgroundFetch:   "requiredNetworkType": 0,
02-24 16:14:26.322 25004 25004 D TSBackgroundFetch:   "requiresBatteryNotLow": false,
02-24 16:14:26.322 25004 25004 D TSBackgroundFetch:   "requiresCharging": false,
02-24 16:14:26.322 25004 25004 D TSBackgroundFetch:   "requiresDeviceIdle": false,
02-24 16:14:26.322 25004 25004 D TSBackgroundFetch:   "requiresStorageNotLow": false,
02-24 16:14:26.322 25004 25004 D TSBackgroundFetch:   "startOnBoot": true,
02-24 16:14:26.322 25004 25004 D TSBackgroundFetch:   "jobService": "com.transistorsoft.flutter.backgroundfetch.HeadlessTask",
02-24 16:14:26.322 25004 25004 D TSBackgroundFetch:   "forceAlarmManager": false,
02-24 16:14:26.322 25004 25004 D TSBackgroundFetch:   "periodic": true,
02-24 16:14:26.322 25004 25004 D TSBackgroundFetch:   "delay": -1
02-24 16:14:26.322 25004 25004 D TSBackgroundFetch: }
```

**Additional context**

**Comment by christocracy** [comment]
You are not calling .registerHeadlessTask.

see the api docs Config.enableHeadless and carefully follow all the required steps.

**Comment by miguelflores1993** [comment]
> You are not calling .registerHeadlessTask.
> 
> see the api docs Config.enableHeadless and carefully follow all the required steps.

I tell you that I have implementing registerHeadlessTask
I forgot to mention it in Plugin config
A few months ago it was working fine, and now it only works in the foreground or background.

![image](https://user-images.githubusercontent.com/67565934/155628708-8606d218-a647-4ea2-b388-a731da28969d.png)

**Comment by christocracy** [comment]
> I forgot to mention it in Plugin config

If you don’t show all applicable code, I can only assume you’re doing it wrong.

**Comment by christocracy** [comment]
Also, the issue template asked you to post the result of `$ flutter doctor`.

You ignored that.

**Comment by miguelflores1993** [comment]
> Also, the issue template asked you to post the result of `$ flutter doctor`.
> 
> You ignored that.

git del proyecto.
[deltax github](https://github.com/miguelhangelh/detaxla
)
FILES involved in configuration

```
1.- CONFIGURE 
lib\app_dev.dart

2. START 
Lib\features\operation\presentation\bloc\operation_bloc.dart
```

I don't know if you can understand my project, but that would be all the configuration I've done and it worked like 3 months ago, I didn't really touch anything, other than updating versions of flutter and the library itself.

It would be supportive, help me, since I have a license purchased with you

DOCTOR

[√] Flutter (Channel stable, 2.10.0, on Microsoft Windows [VersiÃ³n 10.0.22000.493], locale es-BO)
[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[√] Chrome - develop for the web
[√] Android Studio (version 2021.1)
[√] VS Code (version 1.64.2)
[√] Connected device (3 available)
[√] HTTP Host Availability

**Comment by miguelflores1993** [comment]
@christocracy  sorry fail LINK PROYECT


This is the real
[URL PROYECTO](https://github.com/miguelhangelh/dx_flutter)

**Comment by miguelflores1993** [comment]
@christocracy

a thousand apologies, I was wrong again....

this is link.
I'm sorry a thousand times again.

This is the real
[URL PROYECTO](https://github.com/miguelhangelh/dxds)

**Comment by miguelflores1993** [comment]
I have this last log, will it be related to the library?


02-25 00:01:19.431  8587  8587 D TSBackgroundFetch: - Background Fetch event received: com.deltaxlat.appdriver
02-25 00:01:19.447  8587  8587 D TSBackgroundFetch: 💀 [HeadlessTask com.deltaxlat.appdriver]
02-25 00:01:19.531  8587  8587 D TSBackgroundFetch: [HeadlessTask] waiting for client to initialize
02-25 00:01:19.699  8587  8685 E flutter : [ERROR:flutter/shell/common/shell.cc(93)] Dart Unhandled Exception: NoSuchMethodError: No top-level getter '_Smc' declared.
02-25 00:01:19.699  8587  8685 E flutter : Receiver: top-level
02-25 00:01:19.699  8587  8685 E flutter : Tried calling: _Smc, stack trace: Warning: This VM has been configured to produce stack traces that violate the Dart standard.
02-25 00:01:19.699  8587  8685 E flutter : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
02-25 00:01:19.699  8587  8685 E flutter : pid: 8587, tid: 8685, name Unknown
02-25 00:01:19.699  8587  8685 E flutter : build_id: 'aed21ea8f9f60429c5ceff9c52da6de6'
02-25 00:01:19.699  8587  8685 E flutter : isolate_dso_base: 7ca8a8d000, vm_dso_base: 7ca8a8d000
02-25 00:01:19.699  8587  8685 E flutter : isolate_instructions: 7ca8d05d70, vm_instructions: 7ca8d01000
02-25 00:01:19.699  8587  8685 E flutter :     #00 abs 0000007ca8d0ce8b virt 000000000027fe8b _kDartIsolateSnapshotInstructions+0x711b
02-25 00:01:19.699  8587  8685 E flutter :
02-25 00:01:19.699  8587  8685 E flutter : [ERROR:flutter/runtime/dart_isolate.cc(681)] Could not resolve main entrypoint function.
02-25 00:01:19.699  8587  8685 E flutter : [ERROR:flutter/runtime/dart_isolate.cc(165)] Could not run the run main Dart entrypoint.
02-25 00:01:19.701  8587  8685 E flutter : [ERROR:flutter/runtime/runtime_controller.cc(381)] Could not create root isolate.
02-25 00:01:19.701  8587  8685 E flutter : [ERROR:flutter/shell/common/shell.cc(580)] Could not launch engine with configuration.
02-25 00:01:19.764  1698  1698 D TSBackgroundFetch: - Background Fetch event received: com.deltaxlat.appdriver
02-25 00:01:19.766  1698  1698 D TSBackgroundFetch: 💀 [HeadlessTask com.deltaxlat.appdriver]
02-25 00:01:19.781  1698  1698 D TSBackgroundFetch: - finish: com.deltaxlat.appdriver
02-25 00:01:19.781  1698  1698 D TSBackgroundFetch: - jobFinished
02-25 00:01:19.858  1698  1698 D TSBackgroundFetch: - Background Fetch event received: flutter_background_fetch
02-25 00:01:19.858  1698  1698 D TSBackgroundFetch: 💀 [HeadlessTask flutter_background_fetch]
02-25 00:01:19.862  1698  1698 D TSBackgroundFetch: - finish: flutter_background_fetch
02-25 00:01:19.862  1698  1698 D TSBackgroundFetch: - jobFinished

**Comment by christocracy** [comment]
>Unhandled Exception: NoSuchMethodError: No top-level getter '_Smc' declared.
02-25 00:01:19.699 [8587 8685](tel:8587 8685) E flutter : Receiver: top-level

This has nothing to do with the plugin.

please create for me a simple *HelloWorld* app which reproduces the error.  Share it to me in a public GitHub repo.

**Comment by miguelflores1993** [comment]
Hi, thanks for the help.

I am going to prepare an application, with my own configurations and versions of android, gradle, etc.

> > Unhandled Exception: NoSuchMethodError: No top-level getter '_Smc' declared.
> > 02-25 00:01:19.699 [8587 8685](tel:8587 8685) E flutter : Receiver: top-level
> 
> This has nothing to do with the plugin.
> 
> please create for me a simple _HelloWorld_ app which reproduces the error. Share it to me in a public GitHub repo.

**Comment by miguelflores1993** [comment]
**CONFIG**
```
FLUTTER : 2.10.0
distributionUrl=https\://services.gradle.org/distributions/gradle-6.7-all.zip
classpath 'com.android.tools.build:gradle:4.1.0'
flutter_background_geolocation: ^4.3.4
background_fetch: ^1.0.3
```

**I just created a project from scratch and the same problem exists.**
**HERE YOU HAVE THE REPOSITORY**
[PROYECT GITHUB](https://github.com/miguelhangelh/pruebaconfiggps)

**Comment by miguelflores1993** [comment]
> > Unhandled Exception: NoSuchMethodError: No top-level getter '_Smc' declared.
> > 02-25 00:01:19.699 [8587 8685](tel:8587 8685) E flutter : Receiver: top-level
> 
> This has nothing to do with the plugin.
> 
> please create for me a simple _HelloWorld_ app which reproduces the error. Share it to me in a public GitHub repo.

you could see it? or I'm still waiting, I would like to know if I configured it wrong.

**Comment by miguelflores1993** [comment]
> > > Unhandled Exception: NoSuchMethodError: No top-level getter '_Smc' declared.
> > > 02-25 00:01:19.699 [8587 8685](tel:8587 8685) E flutter : Receiver: top-level
> > 
> > 
> > This has nothing to do with the plugin.
> > please create for me a simple _HelloWorld_ app which reproduces the error. Share it to me in a public GitHub repo.
> 
> you could see it? or am i still waiting? I would like to know if I configured it wrong.

**Comment by miguelflores1993** [comment]
@christocracy 
my friend I just caught the underlying problem of this.

**I use Flutter 2.10.2
I can't downgrade because I already have nullSafety activated in my production project.**

> the example project of yours if it works fine with Flutter 2.2.3
> all perfect!.

> **I just Migrated your example project to flutter 2.10.2**

```
and it has the same error or failed behavior that I am facing on many devices.

```

**Comment by christocracy** [comment]
With */example* app:
```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.3, on macOS 12.2.1 21D62 darwin-x64, locale en-CA)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] Connected device (4 available)
[✓] HTTP Host Availability
```

```
$ ./scripts/simulate-fetch

03-10 10:46:46.284 22300 22300 D TSBackgroundFetch: - Background Fetch event received: flutter_background_fetch
03-10 10:46:46.301 22300 22300 D TSBackgroundFetch: 💀 [HeadlessTask flutter_background_fetch]
03-10 10:46:46.322 22300 22300 D TSBackgroundFetch: [HeadlessTask] waiting for client to initialize
03-10 10:46:47.364 22300 22300 I TSBackgroundFetch: $ initialized
03-10 10:46:47.424 22300 22362 I flutter : [BackgroundFetch] HeadlessTask: flutter_background_fetch
03-10 10:46:47.522 22300 22362 I flutter : [BackgroundFetch] count: 1342
03-10 10:46:47.524 22300 22300 D TSBackgroundFetch: - finish: flutter_background_fetch
03-10 10:46:47.524 22300 22300 D TSBackgroundFetch: - jobFinished
```

**Comment by miguelflores1993** [comment]
I don't know what else to do, I don't understand why it fails, will it be my phone?
I always get this error when I kill the app
My setup is the same as the example.

```
03-10 00:01:19.431 8587 8587 D TSBackgroundFetch: - Background Fetch event received: com.deltaxlat.appdriver
03-10 00:01:19.447 8587 8587 D TSBackgroundFetch: 💀 [HeadlessTask com.deltaxlat.appdriver]
03-10 00:01:19.531 8587 8587 D TSBackgroundFetch: [HeadlessTask] waiting for client to initialize
03-10 00:01:19.699 8587 8685 E flutter : [ERROR:flutter/shell/common/shell.cc(93)] Dart Unhandled Exception: NoSuchMethodError: No top-level getter '_Smc' declared.
03-10 00:01:19.699 8587 8685 E flutter : Receiver: top-level
03-10 00:01:19.699 8587 8685 E flutter : Tried calling: _Smc, stack trace: Warning: This VM has been configured to produce stack traces that violate the Dart standard.
03-10 00:01:19.699 8587 8685 E flutter : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
03-10 00:01:19.699 8587 8685 E flutter : pid: 8587, tid: 8685, name Unknown
03-10 00:01:19.699 8587 8685 E flutter : build_id: 'aed21ea8f9f60429c5ceff9c52da6de6'
03-10 00:01:19.699 8587 8685 E flutter : isolate_dso_base: 7ca8a8d000, vm_dso_base: 7ca8a8d000
03-10 00:01:19.699 8587 8685 E flutter : isolate_instructions: 7ca8d05d70, vm_instructions: 7ca8d01000
03-10 00:01:19.699 8587 8685 E flutter : #00 abs 0000007ca8d0ce8b virt 000000000027fe8b _kDartIsolateSnapshotInstructions+0x711b
03-10 00:01:19.699 8587 8685 E flutter :
03-10 00:01:19.699 8587 8685 E flutter : [ERROR:flutter/runtime/dart_isolate.cc(681)] Could not resolve main entrypoint function.
03-10 00:01:19.699 8587 8685 E flutter : [ERROR:flutter/runtime/dart_isolate.cc(165)] Could not run the run main Dart entrypoint.
03-10 00:01:19.701 8587 8685 E flutter : [ERROR:flutter/runtime/runtime_controller.cc(381)] Could not create root isolate.
03-10 00:01:19.701 8587 8685 E flutter : [ERROR:flutter/shell/common/shell.cc(580)] Could not launch engine with configuration.
03-10 00:01:19.764 1698 1698 D TSBackgroundFetch: - Background Fetch event received: com.deltaxlat.appdriver
03-10 00:01:19.766 1698 1698 D TSBackgroundFetch: 💀 [HeadlessTask com.deltaxlat.appdriver]
03-10 00:01:19.781 1698 1698 D TSBackgroundFetch: - finish: com.deltaxlat.appdriver
03-10 00:01:19.781 1698 1698 D TSBackgroundFetch: - jobFinished
03-10 00:01:19.858 1698 1698 D TSBackgroundFetch: - Background Fetch event received: flutter_background_fetch
03-10 00:01:19.858 1698 1698 D TSBackgroundFetch: 💀 [HeadlessTask flutter_background_fetch]
03-10 00:01:19.862 1698 1698 D TSBackgroundFetch: - finish: flutter_background_fetch
03-10 00:01:19.862 1698 1698 D TSBackgroundFetch: - jobFinished
```
